### ISSUE TITLE
Error while starting on Arm Android Smartphone with termux within tmux

### ISSUE THREAD

**Issue by 3151** [marado/TalkerNode#137]
~/TalkerNode $ PORT=3333 node TalkerNode.js
/data/data/com.termux/files/home/TalkerNode/TalkerNode.js:7
var chalk = require('chalk');
            ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /data/data/com.termux/files/home/node_modules/chalk/source/index.js from /data/data/com.termux/files/home/TalkerNode/TalkerNode.js not supported.
Instead change the require of index.js in /data/data/com.termux/files/home/TalkerNode/TalkerNode.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/data/data/com.termux/files/home/TalkerNode/TalkerNode.js:7:13) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v17.4.0
~/TalkerNode $

**Comment by marado** [comment]
According to https://github.com/chalk/chalk/releases/tag/v5.0.0 there are breaking changes, and until TalkerNode adjusts to them (including depending on node >= 12.20), the solution is to specifically depend on chalk 4.

**Comment by marado** [comment]
Fixed, thanks a ton for reporting this!
