### ISSUE TITLE
Create commands aliases

### ISSUE THREAD

**Issue by marado** [marado/TalkerNode#26]
.to and .sayto , .sto and .shoutto , several commands should be allowed to have more than one "name", without the need to replicate the command file.

**Comment by dissidente** [comment]
#101 

A new attribute was added to the command definition: alias. Although optional, it should be included in the command definition for standardization.

findCommand() now searches for commands following the hierarchy "direct match > weighted partial match > alias direct match". The command alias is always the last to be searched for and only allows for a direct match. Commands may only have one defined alias.

**Comment by marado** [comment]
This is also related with #103 and #85 , that actually implement the commands we wish to later add aliases to.

**Comment by marado** [comment]
With #101 the feature to "be able to define command aliases" was implemented. Now the actual aliases should be created as we go. The examples on this issue (.to and .sto, for .sayto and .shoutto), are already mentioned in the issues created to implement those commands in the first place (#85 and #103). Thus, I'm closing the issue.
