### ISSUE TITLE
pick version out of package.json

### ISSUE THREAD

**Issue by marado** [marado/TalkerNode#47]
Now that we have a package.json file, we don't need to have the version hardcoded on TalkerNode.js.

**Comment by qbunt** [comment]
On it!

**Comment by marado** [comment]
Thanks both to @qbunt and @burgwyn for working on this so quickly! I'll actually use a bit from both commits.
There are two other #hacktoberfest issues on this project, if you're interested in something a little less easy :-)
https://github.com/marado/TalkerNode/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest
