### ISSUE TITLE
write access_logs useful for a fail2ban configuration

### ISSUE THREAD

**Issue by marado** [marado/TalkerNode#68]
See amnuts' implementation, as it seems to work quite fine.
Unfortunately open ports are too often attacked, and such a flood protection seems to be a necessity.

**Comment by dissidente** [comment]
Hi @marado . I suggest exploring the use of fail2ban for this feature, perhaps modifying the security log to be compatible and have fail2ban manage the blocking.

**Comment by marado** [comment]
Indeed, making TalkerNode write a sort of access_log or something of the kind, that can be processed by fail2ban, would be enough. Ideally, this feature would be implemented by someone who has experience with fail2ban and knows the best way TalkerNode could produce those logs in order to keep the fail2ban configuration simple.
