### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [marado/TalkerNode#78]
Hi @marado i am a logo designer. i designing logos to opensource projects for contribution. i noticed to the repo hasn't a logo.  What do you think?

![talkernote](https://user-images.githubusercontent.com/36298335/57185841-08bd6080-6edc-11e9-84b9-7fa08bbe4468.jpg)

Readme view;

![talker2](https://user-images.githubusercontent.com/36298335/57185844-31455a80-6edc-11e9-9838-aedbba5cf7cf.png)

**Comment by marado** [comment]
Hi, thanks for the contribution, I really like the logo! The green color is also a great fit, as it is the color most identified with a terminal.

Would you like to create a pull request?

**Comment by reallinfo** [comment]
Of course! I sent a pr. If you need a logo for your other projects, don't hesitate to contact me.

**Comment by marado** [comment]
Merged, thank you very much!
