### ISSUE TITLE
.exa - display the total login time in a more friendly manner

### ISSUE THREAD

**Issue by marado** [marado/TalkerNode#89]
Someone having 3 months, 10 days, 5 hours and 2 minutos of total login time will show as "3 mon", on .exa... which is not very friendly.

**Comment by subhamskm** [comment]
I would like to take up this issue. Can you give me some more info?

**Comment by marado** [comment]
Sure! There isn't much more to be said, however.
As you can see on https://github.com/marado/TalkerNode/blob/master/commands/examine.js#L57 , lines 57 to 76, the time is being calculated correctly, and then displayed by the "friendlyTime" function in the same file. Changing the behavior of friendlyTime should be enough.

Ideally, I guess, it should state "1 year, 2 months, 3 days, 5 hours, five minutes", if the time is over one year, only referring months if the time is at least 1 month, and so on. I'd only mention seconds or milliseconds if the time is less than one minute.

**Comment by subhamskm** [comment]
Can you explain me how to run the app and test the code?

**Comment by marado** [comment]
Hey!

I enhanced the instructions on README a little bit:
https://github.com/marado/TalkerNode/#installation
