### ISSUE TITLE
Don't wait for a .quit to save the total login time

### ISSUE THREAD

**Issue by marado** [marado/TalkerNode#90]
If we have an user connected for a few months without quitting and then the server crashes, or something on that kind, he will loose all that login time, since we're only saving it once the user .q's.

**Comment by subhamskm** [comment]
I am not able to give a name. When I press any key it gives "invalid username...."
![Screenshot (32)](https://user-images.githubusercontent.com/31374351/60393837-42f05a80-9b39-11e9-9951-19eadc49df45.png)

**Comment by marado** [comment]
Interesting... That's new: TalkerNode used to run well on Windows, as well
as deal well with Windows' telnet.

Can you please open a new issue about this? In it, please tell me which
versions of both Windows and Node.js are you using.

Can you also, please, try connecting using a MUD client instead of telnet?
That will help us find out if the problem is on the server running on that
combination of Windows+node version, or on the server generically dealing
with connecions from the telnet from that Windows version.

**Comment by marado** [comment]
Also, are you by any reason using cmder to run telnet? You might be hitting on https://github.com/Maximus5/ConEmu/issues/870 ...

**Comment by marado** [comment]
I'm also seeing a color bleed that shouldn't be there, which leads me to believe you're using (directly or indirectly) powershell to run telnet, with the symptoms of https://github.com/PowerShell/PowerShell/issues/7767 (which would mean you're using a version older than powershell 6.2.0).

**Comment by marado** [comment]
I also tested using powershell 6.2.1 (on GNU/Linux, YMMV) to connect to TalkerNode and didn't reproduce your issue.

**Comment by marado** [comment]
Amnuts has a manual way of doing this, with .save , but maybe we can find a better approach.

**Comment by dissidente** [comment]
My approach would be to use a timer to periodically save the information (ie. hourly), and use the same function for both a manual save command (.save as you suggest) and the on quit saving.

**Comment by marado** [comment]
We can go that route, yes:
[ ] implement .save
[ ] implement a watchdog that runs periodic functions (atm, only .save, hourly)

**Comment by dissidente** [comment]
Implemented in #107
