### ISSUE TITLE
change date presentation format

### ISSUE THREAD

**Issue by marado** [marado/TalkerNode#99]
On several places of the interface (the `.last` command, for example), dates are showing to me in this format:
`Mon Apr 20 2020 23:06:42 GMT+0100 (Western European Summer Time).`
If it said WEST it would be alright, but as it is, it is simply too long (besides useless, and annoying).

**Comment by marado** [comment]
`.exa` is other command that shows this syntax with a less but still annoying effect.

**Comment by dissidente** [comment]
A date formatting function should be created to format in an uniform manner date and time across the code.
I would recommend using https://www.npmjs.com/package/dateformat as it supports several date and time formats

**Comment by marado** [comment]
I am uncertain if adding yet another dependency is needed (after all, we want to uniform everything in one format only, so a simple function to format it appropriately, even if is not one of the standard js calls, should suffice... But I am not against it, either. The biggest task here, IMHO, will be to identify all points in the code where we present a date and want it to be in the uniformed format.

**Comment by dissidente** [comment]
Change implemented in #102
